name: Build

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request_target]

jobs:
  build_repo:
    name: Build ROM US REV 1
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Install package requirements
      run: sudo apt-get install -y git make git build-essential binutils-mips-linux-gnu python3 python3-pip

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: build dependencies
      run: make dependencies

    - name: Get extra dependencies
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.WR64_REPO }}
        token: ${{ secrets.WR64_TOKEN }}
        path: wr64-secret

    - name: Get the dependency
      run: cp -r wr64-secret/baserom.us.z64 ./baserom.us.rev1.z64

    - name: Compile
      run: make extract; make

    - name: Upload progress to Discord
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: python3 tools/upload_progress.py --discord_url ${{ secrets.DISCORD_URL }}
